### ISSUE TITLE
Missing images

### ISSUE THREAD

**Issue by sheri-thomson** [sheri-thomson/fastness-fixer#1]
@charlie-quinn

Images 2 and 3 are not showing up :(

**Comment by charlie-quinn** [comment]
Your `grid.css` file was missing some information to allow the images to exist properly inside of the grid.

- [ ] replace your file with [grid.txt](https://github.com/sheri-thomson/fastness-fixer/files/3917659/grid.txt)

**Comment by charlie-quinn** [comment]
⚠️`Reminder: please close this issue once it has been resolved.`
